apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: slcee-arena
  labels:
    name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongo