apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-replica
  namespace: slcee-arena
spec:
  serviceName: mongo
  replicas: 2
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        selector: mongo
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccount: mongo-account
      containers:
      - name: mongodb
        image: docker.io/mongo:5
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongod
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongod
              key: MONGO_INITDB_ROOT_PASSWORD
        command: ["/bin/sh"]
        args: ["-c", "mongod --replSet=rs0 --bind_ip_all --noauth"]
        resources:
          limits:
            cpu: 1
            memory: 1500Mi
          requests:
            cpu: 1
            memory: 1000Mi
        ports:
        - name: mongo-port
          containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        - name: key
          mountPath: "/etc/keyFile"
          subPath: keyFile
          readOnly: true
      dnsConfig:
        searches:
        - mongo.slcee-arena.svc.cluster.local
      volumes:
      - name: key
        secret:
          secretName: mongod-keyfile
          defaultMode: 384
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi